import { useState, type ReactNode } from "react";
import { Menu, X, ArrowLeft, BookOpen, CalendarCheck, BarChart3, Award, Users, Layers, MessageSquare, Heart, Sparkles, Star } from "lucide-react";
const NAV_LINKS = [{ label: "الرئيسية", href: "#" }, { label: "عن المقرأة", href: "#about" }, { label: "برامجنا", href: "#programs" }, { label: "مميزاتنا", href: "#features" }, { label: "التقويم", href: "/calendar-public" }];
const STATS = [{ value: "+700", label: "طالبة" }, { value: "+300", label: "متطوعة" }, { value: "+10", label: "مسارات وبرامج" }, { value: "+50", label: "حلقة" }];
const FEATURES = [
  { icon: BookOpen, title: "متابعة الحفظ", desc: "تتبّعي تقدمك في حفظ القرآن الكريم خطوةً بخطوة." }, { icon: CalendarCheck, title: "المراجعة والتثبيت", desc: "خطة واضحة للمراجعة اليومية والأسبوعية وتثبيت المحفوظ." }, { icon: Users, title: "صحبة قرآنية", desc: "كوني بين معلمات وطالبات يشاركنك شغف القرآن." }, { icon: Layers, title: "حلقات متنوعة", desc: "مسارات مرنة تناسب مستواك ووقتك وهدفك." }, { icon: Star, title: "عناية بالمعلمات", desc: "أدوات منظمة تعين المعلمات على رعاية طالباتهن." }, { icon: BarChart3, title: "إحصائيات وتقارير", desc: "رؤية واضحة لتقدمك وإنجازاتك في كل مرحلة." }, { icon: Award, title: "بيئة منظمة", desc: "منظومة واحدة تجمع الطالبة والمعلمة والمشرفة." }, { icon: MessageSquare, title: "تواصل مستمر", desc: "رسائل ومتابعة تبقيك قريبة من حلقتك وداعمتك." }
];
const PROGRAMS = ["التثبيت", "حلقات الأمهات", "تصحيح التلاوة", "حلقات الفتيات", "الحفظ والمراجعة", "حلقات الأطفال"];
function Star4({ size = 10, color = "#C4A76A", opacity = 0.7 }) { return <svg width={size} height={size} viewBox="0 0 20 20" fill="none" aria-hidden><path d="M10 0 L11.8 8.2 L20 10 L11.8 11.8 L10 20 L8.2 11.8 L0 10 L8.2 8.2 Z" fill={color} opacity={opacity} /></svg>; }
function Divider({ light = false }) { const color = light ? "#C8CDE8" : "#9EA8CC"; return <div className="flex items-center justify-center gap-3 my-3"><div className="h-px w-10" style={{ background: "linear-gradient(to left, " + color + ", transparent)" }} /><Star4 color={light ? "#FFFFFF" : "#C4A76A"} opacity={light ? 0.6 : 0.8} /><div className="h-px w-10" style={{ background: "linear-gradient(to right, " + color + ", transparent)" }} /></div>; }
function Pill({ children }: { children: ReactNode }) { return <div className="inline-flex items-center gap-1.5 text-xs font-semibold text-[#2B3784] bg-[#ECEEF7] border border-[#C8CDE8] px-3.5 py-1 rounded-full mb-5 tracking-wide"><span className="w-1 h-1 rounded-full bg-[#C4A76A]" />{children}</div>; }
function Logo({ size = 38 }: { size?: number }) { return <img src="/logo.webp" alt="شعار مقرأة سَنا الآي" style={{ width: size, height: size, objectFit: "contain", borderRadius: 10 }} />; }
export default function LandingPage() {
  const [menuOpen, setMenuOpen] = useState(false);
  return <div dir="rtl" className="relative min-h-screen overflow-hidden bg-gradient-to-b from-[#FFF9FC] via-[#F8F7FC] to-[#F1F4FC] text-[#1A2260]" style={{ fontFamily: "'Cairo', 'Tajawal', sans-serif", backgroundImage: "radial-gradient(circle at 8% 16%, rgba(228,231,244,0.9) 0 11rem, transparent 11.1rem), radial-gradient(circle at 92% 34%, rgba(236,238,247,0.95) 0 13rem, transparent 13.1rem), radial-gradient(circle at 14% 61%, rgba(228,231,244,0.75) 0 9rem, transparent 9.1rem), radial-gradient(circle at 88% 78%, rgba(236,238,247,0.85) 0 10rem, transparent 10.1rem), linear-gradient(180deg, #FFF9FC 0%, #F8F7FC 52%, #F1F4FC 100%)" }}><div aria-hidden="true" className="pointer-events-none absolute -top-24 -right-24 z-0 h-80 w-80 rounded-full bg-[#ECEEF7] opacity-70" /><div aria-hidden="true" className="pointer-events-none absolute left-[-9rem] top-[18%] z-0 h-[26rem] w-[26rem] rounded-full bg-[#E4E7F4] opacity-60" /><div aria-hidden="true" className="pointer-events-none absolute -right-24 top-[48%] z-0 h-72 w-72 rounded-full border border-[#C8CDE8] opacity-60" /><div aria-hidden="true" className="pointer-events-none absolute left-12 bottom-24 z-0 h-40 w-40 rounded-full bg-[#ECEEF7] opacity-70" />
    <header className="sticky top-0 z-50 relative" style={{ background: "rgba(248,247,252,0.94)", backdropFilter: "blur(12px)", borderBottom: "1px solid rgba(200,205,232,0.5)" }}><div className="max-w-6xl mx-auto px-5 h-16 flex items-center justify-between gap-4"><a href="#" className="flex items-center gap-2.5 shrink-0"><Logo /><div className="leading-tight"><div className="text-[11px] text-[#9EA8CC] font-medium">مقرأة</div><div className="text-sm font-bold text-[#2B3784]">سَنا الآي</div></div></a><nav className="hidden md:flex items-center gap-7">{NAV_LINKS.map(link => <a key={link.label} href={link.href} className="text-sm text-[#4A5590] hover:text-[#2B3784] transition-colors font-medium">{link.label}</a>)}</nav><div className="flex items-center gap-3"><a href="/login" className="hidden md:inline-flex items-center gap-1.5 text-sm font-bold px-4 py-2 rounded-xl" style={{ background: "#2B3784", color: "#fff" }}>تسجيل الدخول <ArrowLeft className="w-3.5 h-3.5" /></a><button aria-label="فتح القائمة" onClick={() => setMenuOpen(value => !value)} className="md:hidden p-2 rounded-lg text-[#2B3784]">{menuOpen ? <X className="w-5 h-5" /> : <Menu className="w-5 h-5" />}</button></div></div>{menuOpen && <div className="md:hidden px-5 py-4 flex flex-col gap-3" style={{ borderTop: "1px solid rgba(200,205,232,0.5)", background: "#F8F7FC" }}>{NAV_LINKS.map(link => <a key={link.label} href={link.href} onClick={() => setMenuOpen(false)} className="text-sm font-medium text-[#2B3784] py-1">{link.label}</a>)}<a href="/login" className="mt-2 inline-flex items-center justify-center gap-1.5 text-sm font-bold px-4 py-2.5 rounded-xl" style={{ background: "#2B3784", color: "#fff" }}>تسجيل الدخول <ArrowLeft className="w-3.5 h-3.5" /></a></div>}</header>
    <main>
      <section className="relative z-10 overflow-hidden pt-16 pb-24 md:pt-24 md:pb-32"><div className="relative max-w-6xl mx-auto px-5 flex flex-col md:flex-row items-center gap-10 md:gap-20"><div className="flex-1 text-center md:text-right order-2 md:order-1"><div className="inline-flex items-center gap-2 text-xs font-semibold px-3 py-1.5 rounded-full mb-6" style={{ background: "#ECEEF7", color: "#2B3784", border: "1px solid #C8CDE8" }}><span className="w-1.5 h-1.5 rounded-full bg-[#C4A76A]" />بيئة قرآنية إلكترونية نسائية</div><h1 className="text-3xl md:text-[2.75rem] font-bold leading-[1.35] mb-3 text-[#1A2260]">مقرأة <span className="text-[#2B3784]">سَنا الآي</span></h1><p className="text-lg md:text-xl font-semibold mb-3 leading-relaxed text-[#3D4E9C]">في سَنا الآي ورُباه 🌧️</p><Divider /><p className="text-sm md:text-base leading-loose mt-4 mb-8 max-w-md mx-auto md:mx-0 text-[#5A6490]">مساحة آمنة وملهمة لكل فتاة تحب القرآن، وتبحث عن صحبة تعينها على الحفظ والمراجعة والاستمرار.</p><div className="flex flex-col sm:flex-row gap-3 justify-center md:justify-start"><a href="/register" className="inline-flex items-center justify-center gap-2 font-bold text-sm px-7 py-3 rounded-2xl" style={{ background: "#2B3784", color: "#fff", boxShadow: "0 4px 18px rgba(43,55,132,0.25)" }}>انضمي إلى المقرأة <ArrowLeft className="w-4 h-4" /></a><a href="#about" className="inline-flex items-center justify-center gap-2 font-semibold text-sm px-7 py-3 rounded-2xl" style={{ border: "1.5px solid #C8CDE8", color: "#2B3784" }}>تعرّفي علينا</a></div></div><div className="order-1 md:order-2 shrink-0 relative flex items-center justify-center"><div className="absolute w-72 h-72 rounded-full bg-[#ECEEF7] opacity-70" /><div className="absolute w-56 h-56 rounded-full border border-dashed border-[#C8CDE8]" /><div className="absolute top-6 left-10"><Star4 size={8} /></div><div className="absolute bottom-8 right-10"><Star4 size={7} color="#9EA8CC" /></div><img src="/logo.webp" alt="شعار مقرأة سَنا الآي" className="relative z-10 rounded-full" style={{ width: 155, height: 155, objectFit: "cover", background: "#ECEEF7", boxShadow: "0 8px 40px rgba(43,55,132,0.18)", border: "3px solid rgba(200,205,232,0.7)" }} /></div></div></section>
      <section className="py-10 md:py-12" style={{ background: "#2B3784" }}><div className="max-w-4xl mx-auto px-5 grid grid-cols-2 md:grid-cols-4 gap-6">{STATS.map(stat => <div key={stat.label} className="text-center"><div className="text-2xl md:text-3xl font-bold text-white mb-1">{stat.value}</div><div className="text-xs md:text-sm font-medium text-[#C8CDE8]">{stat.label}</div></div>)}</div></section>
      <section id="about" className="relative z-10 py-20 md:py-28 bg-transparent"><div className="max-w-6xl mx-auto px-5 flex flex-col md:flex-row items-center gap-14 md:gap-20"><div className="flex-1"><Pill>هُنا سَنا الآي</Pill><h2 className="text-2xl md:text-3xl font-bold text-[#1A2260] mb-5 leading-snug">هُنا سَنا الآي</h2><p className="text-sm md:text-base leading-loose mb-5 text-[#5A6490]">ابتدأنا رحلتنا قبل أكثر من ست سنوات في مقرأة ريّ جِزال، والريّ تكاثر ونما ليكون سَنا 🌧️</p><p className="text-sm md:text-base leading-loose text-[#5A6490]">ومنذ ذلك الحين، نكبر مع كل طالبة ومعلمة، ونصنع بيئة قرآنية نسائية حانية ومنظمة، تعين على الحفظ والمراجعة وتصحيح التلاوة والإتقان.</p></div></div></section>
      <section className="relative z-10 py-20 md:py-28 bg-transparent"><div className="max-w-5xl mx-auto px-5"><div className="text-center mb-12"><Pill>رسالتنا</Pill><h2 className="text-2xl md:text-3xl font-bold text-[#1A2260]">خطوات صغيرة، وأثر يبقى</h2></div><div className="grid grid-cols-1 md:grid-cols-2 gap-6"><div className="rounded-2xl p-8 bg-white border border-[#C8CDE8]/50"><Heart className="w-6 h-6 text-[#C4A76A] mb-5" /><h3 className="text-base font-bold text-[#1A2260] mb-3">نعتني برحلتك</h3><p className="text-sm leading-loose text-[#5A6490]">نؤمن أن الاستمرار يحتاج إلى بيئة حنونة ومنظمة، لذلك نصنع لك مساحة تشجعك وتحتفي بكل تقدم تحقّقينه.</p></div><div className="rounded-2xl p-8 bg-[#2B3784] shadow-lg"><Sparkles className="w-6 h-6 text-white mb-5" /><h3 className="text-base font-bold text-white mb-3">نطمح لأثر أعظم</h3><p className="text-sm leading-loose text-[#C8CDE8]">نطمح أن نخرّج حافظات متقنات، يحملن القرآن علمًا وخلقًا وأثرًا جميلًا في حياتهن ومجتمعهن.</p></div></div></div></section>
      <section id="features" className="relative z-10 py-20 md:py-28 bg-transparent"><div className="max-w-6xl mx-auto px-5"><div className="text-center mb-14"><Pill>المميزات</Pill><h2 className="text-2xl md:text-3xl font-bold text-[#1A2260] mb-3">كل ما تحتاجينه في رحلتك مع القرآن</h2><p className="text-sm max-w-md mx-auto leading-relaxed text-[#5A6490]">أدوات بسيطة ومنظمة تساعدك على الاستمرار والاقتراب من هدفك كل يوم</p></div><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">{FEATURES.map(feature => <div key={feature.title} className="rounded-2xl p-6 bg-[#F8F7FC] border border-[#C8CDE8]/50"><div className="w-9 h-9 rounded-xl flex items-center justify-center mb-4 bg-[#ECEEF7]"><feature.icon className="w-4 h-4 text-[#3D4E9C]" /></div><h3 className="text-sm font-bold text-[#1A2260] mb-2">{feature.title}</h3><p className="text-xs leading-relaxed text-[#5A6490]">{feature.desc}</p></div>)}</div></div></section>
      <section id="programs" className="relative z-10 py-20 md:py-28 bg-transparent"><div className="max-w-5xl mx-auto px-5 text-center"><Pill>البرامج</Pill><h2 className="text-2xl md:text-3xl font-bold text-[#1A2260] mb-3">مسارات تناسبك</h2><p className="text-sm max-w-md mx-auto leading-relaxed text-[#5A6490] mb-12">اختاري المسار الأقرب إلى احتياجك، وابدئي رحلتك بخطوة واثقة</p><div className="flex flex-wrap justify-center gap-3">{PROGRAMS.map((program, index) => <div key={program} className="min-w-[150px] rounded-2xl px-6 py-5 text-sm font-bold bg-white text-[#2B3784] border border-[#E4DDF0] shadow-[0_8px_24px_rgba(43,55,132,0.08)] hover:-translate-y-1 transition-transform">{program}</div>)}</div></div></section>
      <section className="py-20 md:py-28 relative overflow-hidden bg-[#1A2260]"><div className="relative max-w-2xl mx-auto px-5 text-center"><div className="relative mx-auto mb-4 flex h-28 w-28 items-center justify-center rounded-full border border-[#C8CDE8] bg-[#ECEEF7] shadow-[0_0_30px_rgba(200,205,232,0.28)] before:absolute before:-inset-3 before:rounded-full before:border before:border-[#C8CDE8]/40"><img src="/logo.webp" alt="" style={{ width: 82, height: 82, objectFit: "contain", borderRadius: 12, opacity: 1 }} /></div><Divider light /><h2 className="text-2xl md:text-3xl font-bold text-white mt-5 mb-4">ابدئي رحلتك مع القرآن اليوم</h2><p className="text-sm leading-loose text-[#C8CDE8] mb-8">خطوة واحدة تفصلك عن صحبة جميلة، وبيئة تعينك على الحفظ والإتقان.</p><a href="/register" className="inline-flex items-center justify-center gap-2 font-bold text-sm px-8 py-3 rounded-2xl bg-white text-[#2B3784]">انضمي إلى سَنا الآي <ArrowLeft className="w-4 h-4" /></a></div></section>
    </main>
    <footer className="relative z-10 py-8 bg-transparent border-t border-[#C8CDE8]/50"><div className="max-w-6xl mx-auto px-5 flex flex-col sm:flex-row items-center justify-between gap-3 text-xs text-[#5A6490]"><div className="flex items-center gap-2"><Logo size={26} /><span>مقرأة سَنا الآي</span></div><span>كُل الحقوق محفوظة لقائدة المقرأة</span></div></footer>
  </div>;
}
