import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import usersRouter from "./users";
import circlesRouter from "./circles";
import studentsRouter from "./students";
import recordsRouter from "./records";
import statsRouter from "./stats";
import attendanceRouter from "./attendance";
import dataEntryRouter from "./dataEntry";
import registrationRouter from "./registration";
import exportRouter from "./export";
import messagesRouter from "./messages";
import tracksRouter from "./tracks";
import teacherAbsencesRouter from "./teacherAbsences";
import supervisorTasksRouter from "./supervisorTasks";
import calendarEventsRouter from "./calendarEvents";
import storeRouter from "./store";
import examRecordsRouter from "./examRecords";
import badgesRouter from "./badges";
import teacherRotationRouter from "./teacherRotation";
import shortcomingsRouter from "./shortcomings";
import stumblingStatsRouter from "./stumblingStats";
import studentGoalsRouter from "./studentGoals";
import deputyTasksRouter from "./deputyTasks";
import deputyCircleVisitsRouter from "./deputyCircleVisits";
import setupRouter from "./setup";
import registrationApprovalRouter from "./registrationApproval";
import lowMemorizationAlertsRouter from "./lowMemorizationAlerts";
import dataEntryAssignmentsRouter from "./dataEntryAssignments";
import dataEntrySessionsRouter from "./dataEntrySessions";
import reportsRouter from "./reports";
import whiteLabelRouter from "./whiteLabel";
import schoolConfigRouter from "./schoolConfig";
import firstSetupRouter from "./firstSetup";
import adminRouter from "./admin";
import registrationStudentsRouter from "./registrationStudents";
import reviewPlansRouter from "./reviewPlans";
import settingsRouter from "./settings";
import certificatesRouter from "./certificates";

const router: IRouter = Router();

router.use(setupRouter);
router.use(healthRouter);
router.use(authRouter);
router.use(usersRouter);
router.use(circlesRouter);
router.use(studentsRouter);
router.use(recordsRouter);
router.use(statsRouter);
router.use(attendanceRouter);
router.use(dataEntryRouter);
router.use(registrationRouter);
router.use(exportRouter);
router.use(messagesRouter);
router.use(tracksRouter);
router.use(teacherAbsencesRouter);
router.use(supervisorTasksRouter);
router.use(calendarEventsRouter);
router.use(storeRouter);
router.use(examRecordsRouter);
router.use(badgesRouter);
router.use(teacherRotationRouter);
router.use(shortcomingsRouter);
router.use(stumblingStatsRouter);
router.use(studentGoalsRouter);
router.use(deputyTasksRouter);
router.use(deputyCircleVisitsRouter);
router.use(registrationApprovalRouter);
router.use(lowMemorizationAlertsRouter);
router.use(dataEntryAssignmentsRouter);
router.use(dataEntrySessionsRouter);
router.use(reportsRouter);
router.use(whiteLabelRouter);
router.use(schoolConfigRouter);
router.use(firstSetupRouter);
router.use(adminRouter);
router.use(registrationStudentsRouter);
router.use(reviewPlansRouter);
router.use(settingsRouter);
router.use(certificatesRouter);

export default router;
