export interface Country {
  name: string;
  dialCode: string;
}

export const COUNTRIES: Country[] = [
  // الخليج العربي
  { name: "السعودية", dialCode: "+966" },
  { name: "الإمارات", dialCode: "+971" },
  { name: "الكويت", dialCode: "+965" },
  { name: "قطر", dialCode: "+974" },
  { name: "البحرين", dialCode: "+973" },
  { name: "عُمان", dialCode: "+968" },
  // المشرق والشام
  { name: "الأردن", dialCode: "+962" },
  { name: "فلسطين", dialCode: "+970" },
  { name: "لبنان", dialCode: "+961" },
  { name: "سوريا", dialCode: "+963" },
  { name: "العراق", dialCode: "+964" },
  // وادي النيل
  { name: "مصر", dialCode: "+20" },
  { name: "السودان", dialCode: "+249" },
  // المغرب العربي
  { name: "ليبيا", dialCode: "+218" },
  { name: "تونس", dialCode: "+216" },
  { name: "الجزائر", dialCode: "+213" },
  { name: "المغرب", dialCode: "+212" },
  { name: "موريتانيا", dialCode: "+222" },
  // اليمن
  { name: "اليمن", dialCode: "+967" },
  // أفريقيا
  { name: "الصومال", dialCode: "+252" },
  { name: "جيبوتي", dialCode: "+253" },
  { name: "جزر القمر", dialCode: "+269" },
  { name: "إريتريا", dialCode: "+291" },
  { name: "إثيوبيا", dialCode: "+251" },
  { name: "كينيا", dialCode: "+254" },
  { name: "تنزانيا", dialCode: "+255" },
  { name: "أوغندا", dialCode: "+256" },
  { name: "رواندا", dialCode: "+250" },
  { name: "نيجيريا", dialCode: "+234" },
  { name: "غانا", dialCode: "+233" },
  { name: "السنغال", dialCode: "+221" },
  { name: "مالي", dialCode: "+223" },
  { name: "النيجر", dialCode: "+227" },
  { name: "بوركينا فاسو", dialCode: "+226" },
  { name: "ساحل العاج", dialCode: "+225" },
  { name: "غينيا", dialCode: "+224" },
  { name: "الكاميرون", dialCode: "+237" },
  { name: "تشاد", dialCode: "+235" },
  { name: "جنوب أفريقيا", dialCode: "+27" },
  { name: "زيمبابوي", dialCode: "+263" },
  { name: "موزمبيق", dialCode: "+258" },
  { name: "مدغشقر", dialCode: "+261" },
  // آسيا الوسطى والجنوبية
  { name: "تركيا", dialCode: "+90" },
  { name: "إيران", dialCode: "+98" },
  { name: "أفغانستان", dialCode: "+93" },
  { name: "باكستان", dialCode: "+92" },
  { name: "الهند", dialCode: "+91" },
  { name: "بنغلاديش", dialCode: "+880" },
  { name: "سريلانكا", dialCode: "+94" },
  { name: "نيبال", dialCode: "+977" },
  // آسيا الجنوبية الشرقية
  { name: "ماليزيا", dialCode: "+60" },
  { name: "إندونيسيا", dialCode: "+62" },
  { name: "الفلبين", dialCode: "+63" },
  { name: "تايلاند", dialCode: "+66" },
  { name: "سنغافورة", dialCode: "+65" },
  { name: "بروناي", dialCode: "+673" },
  // آسيا الشرقية
  { name: "الصين", dialCode: "+86" },
  { name: "اليابان", dialCode: "+81" },
  { name: "كوريا الجنوبية", dialCode: "+82" },
  // وسط آسيا
  { name: "أذربيجان", dialCode: "+994" },
  { name: "كازاخستان", dialCode: "+7" },
  { name: "أوزبكستان", dialCode: "+998" },
  { name: "تركمانستان", dialCode: "+993" },
  { name: "طاجيكستان", dialCode: "+992" },
  { name: "قيرغيزستان", dialCode: "+996" },
  // أوروبا
  { name: "المملكة المتحدة", dialCode: "+44" },
  { name: "فرنسا", dialCode: "+33" },
  { name: "ألمانيا", dialCode: "+49" },
  { name: "إيطاليا", dialCode: "+39" },
  { name: "إسبانيا", dialCode: "+34" },
  { name: "هولندا", dialCode: "+31" },
  { name: "بلجيكا", dialCode: "+32" },
  { name: "السويد", dialCode: "+46" },
  { name: "النرويج", dialCode: "+47" },
  { name: "الدنمارك", dialCode: "+45" },
  { name: "فنلندا", dialCode: "+358" },
  { name: "سويسرا", dialCode: "+41" },
  { name: "النمسا", dialCode: "+43" },
  { name: "البرتغال", dialCode: "+351" },
  { name: "اليونان", dialCode: "+30" },
  { name: "بولندا", dialCode: "+48" },
  { name: "رومانيا", dialCode: "+40" },
  { name: "روسيا", dialCode: "+7" },
  { name: "أوكرانيا", dialCode: "+380" },
  { name: "التشيك", dialCode: "+420" },
  { name: "المجر", dialCode: "+36" },
  { name: "بلغاريا", dialCode: "+359" },
  { name: "صربيا", dialCode: "+381" },
  { name: "كرواتيا", dialCode: "+385" },
  // أمريكا الشمالية
  { name: "أمريكا", dialCode: "+1" },
  { name: "كندا", dialCode: "+1" },
  { name: "المكسيك", dialCode: "+52" },
  // أمريكا اللاتينية
  { name: "البرازيل", dialCode: "+55" },
  { name: "الأرجنتين", dialCode: "+54" },
  { name: "كولومبيا", dialCode: "+57" },
  { name: "تشيلي", dialCode: "+56" },
  { name: "بيرو", dialCode: "+51" },
  { name: "فنزويلا", dialCode: "+58" },
  // أوقيانوسيا
  { name: "أستراليا", dialCode: "+61" },
  { name: "نيوزيلندا", dialCode: "+64" },
  // آخر
  { name: "دولة أخرى", dialCode: "" },
];
